//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int Loan_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public decimal Amount { get; set; }
        public string Duration { get; set; }
        public string StartDate { get; set; }
        public string MonthlyInstallment { get; set; }
        public string Month { get; set; }
    }
}
