//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBanking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineBankingDBEntities : DbContext
    {
        public OnlineBankingDBEntities()
            : base("name=OnlineBankingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<complain> complains { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<fundtransfer> fundtransfers { get; set; }
        public virtual DbSet<loan> loans { get; set; }
    }
}
